// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/images/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/[id]').default>>>>
    }
    '/api/images/:id/palettes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/[id]/palettes').default>>>>
    }
    '/api/images': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/index').default>>>>
    }
    '/api/images/upload-url': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload-url.post').default>>>>
    }
    '/api/images/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}