// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/14/2025, 10:35:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/sbecker11/color-palette-app/color-palette-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/plugins/**/*.{js,ts,mjs}","/Users/sbecker11/color-palette-app/color-palette-frontend/composables/**/*.{js,ts,mjs}","/Users/sbecker11/color-palette-app/color-palette-frontend/utils/**/*.{js,ts,mjs}","/Users/sbecker11/color-palette-app/color-palette-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sbecker11/color-palette-app/color-palette-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;